cos:
  COS_ENDPOINT: "https://s3.us-south.cloud-object-storage.appdomain.cloud"  #
  COS_API_KEY_ID: ${COS_API_KEY_ID}  #
  COS_INSTANCE_CRN: ${COS_INSTANCE_CRN} #
SFTP:
  SFTP_HOST: "sftp-emea.gps.ihost.com"
  SFTP_IFP_ID: ${SFTP_IFP_ID}
  SFTP_IFP_PASS: ${SFTP_IFP_PASS}
  SFTP_VDI_ID: ${SFTP_VDI_ID}
  SFTP_VDI_PASS: ${SFTP_VDI_PASS}
  SFTP_PATH: "ifp_dev"